services:
  db:
    image: postgres:15-alpine
    container_name: insight_compass_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-insight_compass_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-insight_compass_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: insight_compass_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: insight_compass_api
    restart: unless-stopped
    dns: # <--- ДОБАВЛЕНО DNS ДЛЯ API
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./app:/app
      - ./.env:/app/.env:ro
    working_dir: / # Если это работает для тебя, можно оставить / или изменить на /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app # Убедись, что PYTHONPATH корректен для твоего working_dir
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-insight_compass_db}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - APP_HOST=${APP_HOST:-0.0.0.0}
      - APP_PORT=${APP_PORT:-8000}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: insight_compass_celery_worker
    restart: unless-stopped
    dns: # <--- ДОБАВЛЕНО DNS ДЛЯ CELERY WORKER
      - 8.8.8.8
      - 1.1.1.1
    working_dir: / # Аналогично api, проверь связку с PYTHONPATH
    command: celery -A app.celery_app worker -l INFO -c 1
    volumes:
      - ./app:/app
      - ./.env:/app/.env:ro
    environment:
      - PYTHONPATH=/app
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-insight_compass_db}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_PHONE_NUMBER_FOR_LOGIN=${TELEGRAM_PHONE_NUMBER_FOR_LOGIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  celery_beat:
    build:
      context: ./app 
      dockerfile: Dockerfile
    container_name: insight_compass_celery_beat
    restart: unless-stopped
    dns: # <--- ДОБАВЛЕНО DNS ДЛЯ CELERY BEAT
      - 8.8.8.8
      - 1.1.1.1
    working_dir: / # Аналогично api, проверь связку с PYTHONPATH
    command: celery -A app.celery_app beat -l INFO 
    volumes:
      - ./app:/app
      - ./.env:/app/.env:ro 
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis 
      - REDIS_PORT=${REDIS_PORT:-6379}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-insight_compass_db}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_PHONE_NUMBER_FOR_LOGIN=${TELEGRAM_PHONE_NUMBER_FOR_LOGIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis 
      - db    

volumes:
  postgres_data:
  redis_data:

# networks: # Если ты используешь кастомные сети, раскомментируй и настрой
#   app_network:
#     driver: bridge