"""add_sentiment_fields_to_posts

Revision ID: 309b21a03da8
Revises: 5f823f5f9e79
Create Date: 2025-05-27 16:33:32.207097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309b21a03da8'
down_revision: Union[str, None] = '5f823f5f9e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавлены отступы
    op.add_column('posts', sa.Column('post_sentiment_label', sa.String(length=50), nullable=True, comment="Метка тональности текста поста (e.g., positive, negative, neutral)"))
    op.add_column('posts', sa.Column('post_sentiment_score', sa.Float(), nullable=True, comment="Числовая оценка тональности текста поста (e.g., от -1 до 1, или вероятность)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавлены отступы
    op.drop_column('posts', 'post_sentiment_score')
    op.drop_column('posts', 'post_sentiment_label')
    # ### end Alembic commands ###